version: "3.4"

services:
  sql2csv:
    container_name: sql2csv
    build: .
    entrypoint: /input/entrypoint.sh
    environment:
      - CONF_FILE=conf.py
    volumes:
      - ./output:/output
      - ./input:/input
